
[brick]
name = "Parquet"
version = "0.1.2"
type = "library"
chplVersion = "2.8.0..2.9.0"
source = "https://github.com/chapel-lang/Parquet"
authors = ["Engin Kayraklioglu", "Shreyas Khandekar", "Ben Harshbarger"]
license = "Apache-2.0"
copyrightYear = "2026"

[dependencies]

[system]
arrow = "19.0.1"
parquet = "19.0.1"
