language: c
os:
  - linux
compiler:
  - gcc

matrix:
  include:
    - name: "checkTomls"
      env: TEST_COMMAND="./util/checkTomls.bash"

  include:
    - name: "check tomlContent"
      env: TEST_COMMAND="./util/makeChapel.bash && chpl ./util/tomlContentCheck.chpl $$ ./util/tomlContentCheck"

script:
  - (eval "$TEST_COMMAND")
