language: c
os:
  - linux
compiler:
  - gcc

matrix:
  jobs:
    stage: Build
      include:
        - name: "make check"
          env: NIGHTLY_TEST_SETTINGS=true QTHREAD_AFFINITY=no HWLOC_HIDE_ERRORS=1 CHPL_SMOKE_SKIP_DOC=true TEST_COMMAND="./util/makeChapel.bash &&  ./util/buildRelease/smokeTest"
    stage: Check
      include:
        - name: "check tomlContent"
          env: TEST_COMMAND="chpl ./util/tomlContentCheck.chpl $$ ./util/tomlContentCheck"
      include:
        - name: "checkTomls"
          env: TEST_COMMAND="./util/checkTomls.bash"

stages:
  -Build
  -Check
script:
  - (eval "$TEST_COMMAND")
