language: c
os:
  - linux
compiler:
  - gcc

matrix:
  include:
    - name: "get chapel"
      env: MAKE_COMMAND='./util/makeChapel'

    - name: "make check"
      env: NIGHTLY_TEST_SETTINGS=true QTHREAD_AFFINITY=no HWLOC_HIDE_EDDORS=1 CHPL_SMOKE_SKIP_DOC=true TEST_COMMAND='./chapel/util/buildRelease/smokeTest'

    - name: "make check-chpldoc && make docs"
      env: NIGHTLY_TEST_SETTINGS=true CHPL_SMOKE_SKIP_MAKE_CHECK=true TEST_COMMAND="./chapel/util/buildRelease/smokeTest"

    - name: "check annotations"
      env: TEST_COMMAND="make test-venv && CHPL_HOME=$PWD ./chapel/util/run-in-venv.bash ./chapel/util/test/check_annotations.py"
      git:
        depth: 100000

    - name: "look for bad runtime calls"
      env: TEST_COMMAND="./chapel/util/devel/lookForBadRTCalls"
      addons:
        apt:
          packages:
          - cscope

script:
  - stage: make
    script: (eval "$MAKE_COMMAND")
  - stage: test
    script: (eval "$TEST_COMMAND")

sudo: false

