language: c
os:
  - linux
compiler:
  - gcc

matrix:
  include:
    - name : 'toml check'
    - env : TEST_COMMAND="chpl .tomlCheck.chpl ./.tomlCheck"

script:
  - (eval "$TEST_COMMAND")


sudo: false
