language: c
os:
  - linux
compiler:
  - gcc

jobs:
  include:
    - stage: Get
      env: GET_COMMAND='./util/makeChapel.bash ;  ./util/tomlContentCheck.chpl"
      script: (eval '$GET_COMMAND')
    - stage: Test
      env: TEST_COMMAND=' ./util/tomlContentCheck'
      script: (eval "$TEST_COMMAND")
sudo: true
