[brick]
name="Dyno"
version="0.1.0"
chplVersion="2.8.0"
type="library"
source="https://github.com/jabraham17/Dyno.git"

authors=["Jade Abraham"]
copyrightYear="2026"
license="Apache-2.0"

docopts = "-Mprereqs/dyno/"

[dependencies]

