[brick]
name = "quickchpl"
version = "1.0.2"
chplVersion = "2.6.0..2.8.0"
license = "MIT"
type = "library"
source = "https://github.com/Jesssullivan/quickchpl"
authors = "Jess Sullivan"

[dependencies]
