[brick]
name="SciChap"
version="0.1.0"
chplVersion="2.8.0"
type="library"
source="git@github.com:jmag722/SciChap.git"
authors=["Jared Magnusson"]
license="BSD-3-Clause"
copyrightYear="2025"

[tool.chpl-language-server]
module-dir="src"

[tool.chplcheck]
disable-rule = ["CamelCaseFunctions"] # unit tests break this convention
