[brick]
name="TerminalColors"
version="0.1.0"
chplVersion="2.7.0"
type="library"
source="git@github.com:jabraham17/TerminalColors.git"

authors=["Jade Abraham"]
copyrightYear="2026"
license="Apache-2.0"

docopts=["--index=docs/index.rst"]

[dependencies]


