name: Mason Registry CI
on:
  pull_request:
    paths:
      - 'Bricks/**'
      - .github/workflows/masonRegCI.yaml
jobs:
  checks_for_package:
    name: Check Package
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
          persist-credentials: false
      - name: Run checkTomlScript
        run: |
          bash ./util/checkTomls.bash
      - name: CI Check package
        run: |
          bash ./util/runMasonCI.bash
